import msSethiGym from 'public/modelMarketPlaceImages/msSethiGym.jpg';
import msSethiSummer from 'public/modelMarketPlaceImages/msSethisummer.jpg';
import msSethiWinter from 'public/modelMarketPlaceImages/msSethiwinter.jpg';
import poonamPandeyGym from 'public/modelMarketPlaceImages/poonamPandeyGym.jpg';
import poonamPandeySummer from 'public/modelMarketPlaceImages/poonamPandeySummer.jpg';
import poonamPandeyWinter from 'public/modelMarketPlaceImages/poonamPandeyWinter.jpg';
import sherlynChopraGym from 'public/modelMarketPlaceImages/sherlynChopraGym.jpg';
import sherlynChopraSummer from 'public/modelMarketPlaceImages/sherlynChoprasummer1.jpg';
import sherlynChopraWinter from 'public/modelMarketPlaceImages/sherlynChopraWinter1.jpg';

import {
  indianModel1BannerImage,
  indianModel1ProfileIcon,
  indianModel2BannerImage,
  indianModel2ProfileIcon,
  indianModel3BannerImage,
  indianModel3ProfileIcon,
  indianModel4BannerImage,
  indianModel4ProfileIcon,
  indianModel5BannerImage,
  indianModel5ProfileIcon,
  indianModel6BannerImage,
  indianModel6ProfileIcon,
  model1,
  model1BannerImage,
  model2,
  model2BannerImage,
  model3,
  model3BannerImage,
  model4,
  model4BannerImage,
  model5,
  model5BannerImage,
  model6,
  model6BannerImage,
  model7,
  model7BannerImage,
  model8,
  model8BannerImage,
  PoonamPandeyBannerImage,
  PoonamPandeyProfileIcon,
  shrelyBannerImage,
  shrelyProfileIcon,
} from '~/index';

export const modelCardData = [
  {
    id: 9,
    name: 'Sophia Silva',
    slug: 'Sophia_Silva',
    icon: model8,
    location: 'Tango in Buenos Aires',
    image: model8BannerImage,
    AboutMe:
      "Hola! I'm Sophia, a tango enthusiast with a heart full of passion. Join me in the sultry embrace of Buenos Aires, where we'll dance the night away, lost in the enchanting rhythm of tango!",
    value: 9,
    views: 4,
    Tease: 45,
    posts: 42,
  },
  {
    id: 10,
    name: 'Isabella Blue',
    slug: 'Isabella_Blue',
    icon: model2,
    location: 'Viva las summer ',
    image: model2BannerImage,
    AboutMe:
      "Hi, I'm Isabella! A beach lover and sun chaser. I'm all about embracing the warmth of summer and living life to the fullest. Join me as we soak up the sun and create unforgettable memories!",
    value: 2,
    views: 3.1,
    Tease: 44,
    posts: 23,
  },
  {
    id: 11,
    name: 'Ruby Spark',
    slug: 'Ruby_Spark',
    icon: model6,
    location: 'Rumba in Havana: Ruby',
    image: model6BannerImage,
    AboutMe:
      "Hola amigos! I'm Ruby, a fiery soul with a zest for life. Join me in the vibrant streets of Havana as we sway to the rhythm of rumba, savoring the flavors and colors of Cuba!",
    value: 4,
    views: 1.5,
    Tease: 65,
    posts: 12,
  },

  {
    id: 12,
    name: 'Alice Gold',
    slug: 'Alice_Gold',
    icon: model4,
    location: 'Cha-Cha in New York: Stella',
    image: model4BannerImage,
    AboutMe:
      "Hey everyone, I'm Alice! A city girl with a passion for dance and fashion. Join me as we groove through the bustling streets of New York, embracing the energy and excitement of the city!",
    value: 8,
    views: 5.5,
    Tease: 59,
    posts: 13,
  },
  {
    id: 13,
    name: 'Poonam Pandey',
    slug: 'Poonam_Pandey',
    icon: PoonamPandeyProfileIcon,
    location: 'Delhi',
    image: PoonamPandeyBannerImage,
    AboutMe:
      "Hello darlings! I'm Poonam, \na bold and adventurous spirit always seeking new thrills.\nHiking and traveling are my passions,capturing the essence of every moment through my lens.\n\nI take pride in my body's beauty and love sharing it with those who appreciate it.\nI'm also a curious soul, fascinated by the depths of human desires.\n\nHot conversations and my hot body are what's waiting for you.Don't waste your time ⌛. \n\nSubscribe and check your DM for an unforgettable journey! 😋",
    value: 3,
    views: 3.3,
    Tease: 47,
    posts: 18,
    ListPrice: 100,
    tokenId: '2000000345658791507',
  },
  {
    id: 14,
    name: 'Samantha Rose',
    slug: 'Samantha_Rose',
    icon: model5,
    location: 'Flamenco in Seville: Scarlett',
    image: model5BannerImage,
    AboutMe:
      "Hola! I'm Samantha, a free spirit with a love for flamenco and Spanish culture. Let's dance our hearts out under the warm Seville sun, immersing ourselves in the passion and rhythm of flamenco!",
    value: 2,
    views: 3.5,
    Tease: 40,
    posts: 35,
  },
  {
    id: 15,
    name: 'Ava adams',
    slug: 'Ava_adams',
    icon: model3,
    location: 'Tango in Paris: Penelope',
    image: model3BannerImage,
    AboutMe:
      "Bonjour! Je m'appelle Ava. Parisian by heart and artist by soul. Let's wander the romantic streets of Paris together, exploring art, culture, and the magic of the city of love!",
    value: 1,
    views: 4.5,
    Tease: 41,
    posts: 42,
  },

  {
    id: 16,
    name: 'Lily Cruz',
    slug: 'Lily_Cruz',
    icon: model7,
    location: 'Samba in Rio de Janeiro: Lily',
    image: model7BannerImage,
    AboutMe:
      "Oi! I'm Lily, a samba queen with a love for Brazilian culture and rhythm. Let's sizzle under the Rio sun, embracing the energy and passion of samba as we dance our way through the streets of Rio!",
    value: 5,
    views: 3.5,
    Tease: 49,
    posts: 22,
  },
  {
    id: 17,
    name: 'Evelyn Green',
    slug: 'Evelyn_Green',
    icon: model1,
    location: 'Viva Las Vegas: Hazel',
    image: model1BannerImage,
    AboutMe:
      "Hey there! I'm Evelyn, a passionate traveler and adventurer. I thrive on exploring new places and cultures, capturing moments through my lens along the way. Let's embark on exciting journeys together!",
    value: 5,
    views: 3.5,
    Tease: 49,
    posts: 32,
  },
];

export const IndianModelCardData = [
  {
    id: 1,
    name: 'Priya Anjali Rai',
    slug: 'Priya_Anjali_Rai',
    icon: indianModel1ProfileIcon,
    location: 'Mumbai',
    image: indianModel1BannerImage,
    AboutMe:
      "Hey there! I'm Priya, \na vibrant and sociable individual who thrives on adventure and connection.\n\nHiking, skiing, and traveling are my passions,allowing me to explore the world take pride \n in my body's aesthetics and enjoy sharing its allure with others.\n\nLet's dive into deep conversations and explore our desires together.\n\nSubscribe now and let me ignite your passions! 😘",
    value: 7,
    views: 3.8,
    Tease: 52,
    posts: 27,
    ListPrice: 80,
    tokenId: '1000000345658791507',
  },
  {
    id: 2,
    name: 'Poonam Pandey',
    slug: 'Poonam_Pandey',
    icon: PoonamPandeyProfileIcon,
    location: 'Delhi',
    image: PoonamPandeyBannerImage,
    AboutMe:
      "Hello darlings! I'm Poonam, \na bold and adventurous spirit always seeking new thrills.\nHiking and traveling are my passions,capturing the essence of every moment through my lens.\n\nI take pride in my body's beauty and love sharing it with those who appreciate it.\nI'm also a curious soul, fascinated by the depths of human desires.\n\nHot conversations and my hot body are what's waiting for you.Don't waste your time ⌛. \n\nSubscribe and check your DM for an unforgettable journey! 😋",
    value: 3,
    views: 3.3,
    Tease: 47,
    posts: 18,
    ListPrice: 100,
    tokenId: '2000000345658791507',
  },
  {
    id: 3,
    name: 'Sahara Knite',
    slug: 'Sahara_Knite',
    icon: indianModel2ProfileIcon,
    location: 'Kolkata',
    image: indianModel2BannerImage,
    AboutMe:
      "Hey there! I'm Sahara, \n\na free-spirited explorer with a passion for adventure.\nHiking and skiing fuel my soul\n\nI embrace the aesthetics of my naked body and enjoy sharing its allure with others.\nI'm also intrigued by people's secret desires.\n\nHot conversations and my hot body are what's waiting for you.Don't waste your time⌛.  \n\nSubscribe and check your DM for an electrifying experience! 🔥",
    value: 2,
    views: 4.2,
    Tease: 38,
    posts: 35,
    ListPrice: 70,
    tokenId: '3000000345658791507',
  },
  {
    id: 4,
    name: 'Persia Pele',
    slug: 'Persia_Pele',
    icon: indianModel3ProfileIcon,
    location: 'Bangalore',
    image: indianModel3BannerImage,
    AboutMe:
      "Namaste! I'm Persia, \n\na fiery spirit with a love for adventure. Hiking, skiing, and traveling are my passions, \nallowing me to capture the essence of life through my photography.\n\nI embrace the aesthetics of my naked body and enjoy sharing its beauty .\n\nI'm also a curious soul, fascinated by the depths of human desires.\nHot conversations and my hot body are what's waiting for you.Don't waste your time ⌛- \n\nSubscribe and check your DM for an exhilarating journey! 😍",
    value: 6,
    views: 5.2,
    Tease: 63,
    posts: 8,
    ListPrice: 60,
    tokenId: '4000000345658791507',
  },
  {
    id: 5,
    name: 'Serena Mann',
    slug: 'Serena_Mann',
    icon: indianModel4ProfileIcon,
    location: 'Chennai',
    image: indianModel4BannerImage,
    AboutMe:
      "Hey there! I'm Serena, \n\nan adventurous soul always seeking new experiences.\nskiing and traveling are my passions ,capturing the beauty of life through my lens.\n\nI take pride in my body's allure I enjoy sharing its beauty with those who appreciate it.\nI'm also a curious soul, fascinated by the depths of human desires.\n\nHot conversations and my hot body are what's waiting for you. Don't waste your time ⌛. \n\nSubscribe and check your DM for an unforgettable adventure! 🌟",
    value: 4,
    views: 4.0,
    Tease: 56,
    posts: 21,
    ListPrice: 30,
    tokenId: '5000000345658791507',
  },
  {
    id: 6,
    name: 'Viva Athena',
    slug: 'Viva_Athena',
    icon: indianModel5ProfileIcon,
    location: 'Hyderabad',
    image: indianModel5BannerImage,
    AboutMe:
      "Namaskaram! I'm Viva, \na vibrant soul with a passion for adventure and connection.\n\nHiking, skiing, and traveling allow me to explore the world and capture its through lens.\nI celebrate the aesthetics of my naked body and enjoy sharing its sensuality with others.\n\nI'm also intrigued by people's secret desires.\nHot conversations and my hot body are what's waiting. Don't waste your time ⌛.  \n\nSubscribe and check your DM for a thrilling experience! 🔥",
    value: 8,
    views: 4.7,
    Tease: 60,
    posts: 16,
    ListPrice: 50,
    tokenId: '6000000345658791507',
  },
  {
    id: 7,
    name: 'Anjali Kara',
    slug: 'Anjali_Kara',
    icon: indianModel6ProfileIcon,
    location: 'Pune',
    image: indianModel6BannerImage,
    AboutMe:
      "Namaskara! I'm Anjali, \na vivacious soul with an appetite for excitement.\nHiking, skiing, and traveling are my passions, \n\nI take pride in my body's allure enjoy sharing its sensuality with those who appreciate it.\n\nI'm also a curious soul, fascinated by the depths of human desires.\nHot conversations and my hot body are what's waiting for you. Don't waste your time ⌛. \n\nSubscribe and check your DM for an electrifying journey! 😘",
    value: 5,
    views: 3.9,
    Tease: 45,
    posts: 30,
    ListPrice: 40,
    tokenId: '7000000345658791507',
  },
  {
    id: 8,
    name: 'Sherlyn Chopra',
    slug: 'Sherlyn_Chopra',
    icon: shrelyProfileIcon,
    location: 'Jaipur',
    image: shrelyBannerImage,
    AboutMe:
      "Hello! I'm Sherlyn, \na dynamic and adventurous soul with a passion for exploration.\n\nI take pride in my body's beauty and enjoy sharing its sensuality with others.\nI'm also intrigued by people's secret desires.\n\nHot conversations and my hot body are what's waiting for you.Don't waste your time⌛.  \n\nSubscribe and check your DM for an unforgettable journey into ecstasy! 😍",
    value: 7,
    views: 4.8,
    Tease: 55,
    posts: 14,
    ListPrice: 90,
    tokenId: '8000000345658791507',
  },
];

export const MarketPlaceCardData = [
  {
    id: 0,
    name: 'poonam Pandey',
    slug: 'Poonam_Pandey',
    icon: PoonamPandeyProfileIcon,
    value: 3,
    views: 3.3,
    Tease: 47,
    posts: 18,
    images: [
      {
        id: 0,
        collection: 'Gym collection',
        image: poonamPandeyGym,
      },
      {
        id: 1,
        collection: 'summer collection',
        image: poonamPandeySummer,
      },
      {
        id: 2,
        collection: 'Winter collection',
        image: poonamPandeyWinter,
      },
    ],
  },
  {
    id: 1,
    name: 'Viva Athena',
    slug: 'Viva_Athena',
    icon: indianModel5ProfileIcon,
    value: 8,
    views: 4.7,
    Tease: 60,
    posts: 16,
    images: [
      {
        id: 0,
        collection: 'Gym collection',
        image: msSethiGym,
      },
      {
        id: 1,
        collection: 'summer collection',
        image: msSethiSummer,
      },
      {
        id: 2,
        collection: 'Winter collection',
        image: msSethiWinter,
      },
    ],
  },
  {
    id: 2,
    name: 'Sherlyn Chopra',
    slug: 'Sherlyn_Chopra',
    icon: shrelyProfileIcon,
    value: 7,
    views: 4.8,
    Tease: 55,
    posts: 14,
    images: [
      {
        id: 0,
        collection: 'Gym collection',
        image: sherlynChopraGym,
      },
      {
        id: 1,
        collection: 'summer collection',
        image: sherlynChopraSummer,
      },
      {
        id: 2,
        collection: 'Winter collection',
        image: sherlynChopraWinter,
      },
    ],
  },
  {
    id: 3,
    name: 'poonamPandey',
    slug: 'Poonam_Pandey',
    icon: PoonamPandeyProfileIcon,
    value: 3,
    views: 3.3,
    Tease: 47,
    posts: 18,
    images: [
      {
        id: 0,
        collection: 'Gym collection',
        image: poonamPandeyGym,
      },
      {
        id: 1,
        collection: 'summer collection',
        image: poonamPandeySummer,
      },
      {
        id: 2,
        collection: 'Winter collection',
        image: poonamPandeyWinter,
      },
    ],
  },
  {
    id: 4,
    name: 'Viva Athena',
    slug: 'Viva_Athena',
    icon: indianModel5ProfileIcon,
    value: 8,
    views: 4.7,
    Tease: 60,
    posts: 16,
    images: [
      {
        id: 0,
        collection: 'Gym collection',
        image: msSethiGym,
      },
      {
        id: 1,
        collection: 'summer collection',
        image: msSethiSummer,
      },
      {
        id: 2,
        collection: 'Winter collection',
        image: msSethiWinter,
      },
    ],
  },
  {
    id: 5,
    name: 'Sherlyn Chopra',
    slug: 'Sherlyn_Chopra',
    icon: shrelyProfileIcon,
    value: 7,
    views: 4.8,
    Tease: 55,
    posts: 14,
    images: [
      {
        id: 0,
        collection: 'Gym collection',
        image: sherlynChopraGym,
      },
      {
        id: 1,
        collection: 'summer collection',
        image: sherlynChopraSummer,
      },
      {
        id: 2,
        collection: 'Winter collection',
        image: sherlynChopraWinter,
      },
    ],
  },
];

export const allModelData = [
  {
    id: 1,
    name: 'Priya Anjali Rai',
    slug: 'Priya_Anjali_Rai',
    icon: indianModel1ProfileIcon,
    location: 'Mumbai',
    image: indianModel1BannerImage,
    AboutMe:
      "Hey there! I'm Priya, \na vibrant and sociable individual who thrives on adventure and connection.\n\nHiking, skiing, and traveling are my passions,allowing me to explore the world take pride \n in my body's aesthetics and enjoy sharing its allure with others.\n\nLet's dive into deep conversations and explore our desires together.\n\nSubscribe now and let me ignite your passions! 😘",
    value: 7,
    views: 3.8,
    Tease: 52,
    posts: 27,
    ListPrice: 80,
    tokenId: '1000000345658791507',
  },
  {
    id: 2,
    name: 'Poonam Pandey',
    slug: 'Poonam_Pandey',
    icon: PoonamPandeyProfileIcon,
    location: 'Delhi',
    image: PoonamPandeyBannerImage,
    AboutMe:
      "Hello darlings! I'm Poonam, \na bold and adventurous spirit always seeking new thrills.\nHiking and traveling are my passions,capturing the essence of every moment through my lens.\n\nI take pride in my body's beauty and love sharing it with those who appreciate it.\nI'm also a curious soul, fascinated by the depths of human desires.\n\nHot conversations and my hot body are what's waiting for you.Don't waste your time ⌛. \n\nSubscribe and check your DM for an unforgettable journey! 😋",
    value: 3,
    views: 3.3,
    Tease: 47,
    posts: 18,
    ListPrice: 100,
    tokenId: '2000000345658791507',
  },
  {
    id: 3,
    name: 'Sahara Knite',
    slug: 'Sahara_Knite',
    icon: indianModel2ProfileIcon,
    location: 'Kolkata',
    image: indianModel2BannerImage,
    AboutMe:
      "Hey there! I'm Sahara, \n\na free-spirited explorer with a passion for adventure.\nHiking and skiing fuel my soul\n\nI embrace the aesthetics of my naked body and enjoy sharing its allure with others.\nI'm also intrigued by people's secret desires.\n\nHot conversations and my hot body are what's waiting for you.Don't waste your time⌛.  \n\nSubscribe and check your DM for an electrifying experience! 🔥",
    value: 2,
    views: 4.2,
    Tease: 38,
    posts: 35,
    ListPrice: 70,
    tokenId: '3000000345658791507',
  },
  {
    id: 4,
    name: 'Persia Pele',
    slug: 'Persia_Pele',
    icon: indianModel3ProfileIcon,
    location: 'Bangalore',
    image: indianModel3BannerImage,
    AboutMe:
      "Namaste! I'm Persia, \n\na fiery spirit with a love for adventure. Hiking, skiing, and traveling are my passions, \nallowing me to capture the essence of life through my photography.\n\nI embrace the aesthetics of my naked body and enjoy sharing its beauty .\n\nI'm also a curious soul, fascinated by the depths of human desires.\nHot conversations and my hot body are what's waiting for you.Don't waste your time ⌛- \n\nSubscribe and check your DM for an exhilarating journey! 😍",
    value: 6,
    views: 5.2,
    Tease: 63,
    posts: 8,
    ListPrice: 60,
    tokenId: '4000000345658791507',
  },
  {
    id: 5,
    name: 'Serena Mann',
    slug: 'Serena_Mann',
    icon: indianModel4ProfileIcon,
    location: 'Chennai',
    image: indianModel4BannerImage,
    AboutMe:
      "Hey there! I'm Serena, \n\nan adventurous soul always seeking new experiences.\nskiing and traveling are my passions ,capturing the beauty of life through my lens.\n\nI take pride in my body's allure I enjoy sharing its beauty with those who appreciate it.\nI'm also a curious soul, fascinated by the depths of human desires.\n\nHot conversations and my hot body are what's waiting for you. Don't waste your time ⌛. \n\nSubscribe and check your DM for an unforgettable adventure! 🌟",
    value: 4,
    views: 4.0,
    Tease: 56,
    posts: 21,
    ListPrice: 30,
    tokenId: '5000000345658791507',
  },
  {
    id: 6,
    name: 'Viva Athena',
    slug: 'Viva_Athena',
    icon: indianModel5ProfileIcon,
    location: 'Hyderabad',
    image: indianModel5BannerImage,
    AboutMe:
      "Namaskaram! I'm Viva, \na vibrant soul with a passion for adventure and connection.\n\nHiking, skiing, and traveling allow me to explore the world and capture its through lens.\nI celebrate the aesthetics of my naked body and enjoy sharing its sensuality with others.\n\nI'm also intrigued by people's secret desires.\nHot conversations and my hot body are what's waiting. Don't waste your time ⌛.  \n\nSubscribe and check your DM for a thrilling experience! 🔥",
    value: 8,
    views: 4.7,
    Tease: 60,
    posts: 16,
    ListPrice: 50,
    tokenId: '6000000345658791507',
  },
  {
    id: 7,
    name: 'Anjali Kara',
    slug: 'Anjali_Kara',
    icon: indianModel6ProfileIcon,
    location: 'Pune',
    image: indianModel6BannerImage,
    AboutMe:
      "Namaskara! I'm Anjali, \na vivacious soul with an appetite for excitement.\nHiking, skiing, and traveling are my passions, \n\nI take pride in my body's allure enjoy sharing its sensuality with those who appreciate it.\n\nI'm also a curious soul, fascinated by the depths of human desires.\nHot conversations and my hot body are what's waiting for you. Don't waste your time ⌛. \n\nSubscribe and check your DM for an electrifying journey! 😘",
    value: 5,
    views: 3.9,
    Tease: 45,
    posts: 30,
    ListPrice: 40,
    tokenId: '7000000345658791507',
  },
  {
    id: 8,
    name: 'Sherlyn Chopra',
    slug: 'Sherlyn_Chopra',
    icon: shrelyProfileIcon,
    location: 'Jaipur',
    image: shrelyBannerImage,
    AboutMe:
      "Hello! I'm Sherlyn, \na dynamic and adventurous soul with a passion for exploration.\n\nI take pride in my body's beauty and enjoy sharing its sensuality with others.\nI'm also intrigued by people's secret desires.\n\nHot conversations and my hot body are what's waiting for you.Don't waste your time⌛.  \n\nSubscribe and check your DM for an unforgettable journey into ecstasy! 😍",
    value: 7,
    views: 4.8,
    Tease: 55,
    posts: 14,
    ListPrice: 90,
    tokenId: '8000000345658791507',
  },
  {
    id: 9,
    name: 'Sophia Silva',
    slug: 'Sophia_Silva',
    icon: model8,
    location: 'Tango in Buenos Aires',
    image: model8BannerImage,
    AboutMe:
      "Hola! I'm Sophia, a tango enthusiast with a heart full of passion. Join me in the sultry embrace of Buenos Aires, where we'll dance the night away, lost in the enchanting rhythm of tango!",
    value: 9,
    views: 4,
    Tease: 45,
    posts: 42,
  },
  {
    id: 10,
    name: 'Isabella Blue',
    slug: 'Isabella_Blue',
    icon: model2,
    location: 'Viva las summer ',
    image: model2BannerImage,
    AboutMe:
      "Hi, I'm Isabella! A beach lover and sun chaser. I'm all about embracing the warmth of summer and living life to the fullest. Join me as we soak up the sun and create unforgettable memories!",
    value: 2,
    views: 3.1,
    Tease: 44,
    posts: 23,
  },
  {
    id: 11,
    name: 'Ruby Spark',
    slug: 'Ruby_Spark',
    icon: model6,
    location: 'Rumba in Havana: Ruby',
    image: model6BannerImage,
    AboutMe:
      "Hola amigos! I'm Ruby, a fiery soul with a zest for life. Join me in the vibrant streets of Havana as we sway to the rhythm of rumba, savoring the flavors and colors of Cuba!",
    value: 4,
    views: 1.5,
    Tease: 65,
    posts: 12,
  },

  {
    id: 12,
    name: 'Alice Gold',
    slug: 'Alice_Gold',
    icon: model4,
    location: 'Cha-Cha in New York: Stella',
    image: model4BannerImage,
    AboutMe:
      "Hey everyone, I'm Alice! A city girl with a passion for dance and fashion. Join me as we groove through the bustling streets of New York, embracing the energy and excitement of the city!",
    value: 8,
    views: 5.5,
    Tease: 59,
    posts: 13,
  },
  {
    id: 13,
    name: 'Samantha Rose',
    slug: 'Samantha_Rose',
    icon: model5,
    location: 'Flamenco in Seville: Scarlett',
    image: model5BannerImage,
    AboutMe:
      "Hola! I'm Samantha, a free spirit with a love for flamenco and Spanish culture. Let's dance our hearts out under the warm Seville sun, immersing ourselves in the passion and rhythm of flamenco!",
    value: 2,
    views: 3.5,
    Tease: 40,
    posts: 35,
  },
  {
    id: 14,
    name: 'Ava adams',
    slug: 'Ava_adams',
    icon: model3,
    location: 'Tango in Paris: Penelope',
    image: model3BannerImage,
    AboutMe:
      "Bonjour! Je m'appelle Ava. Parisian by heart and artist by soul. Let's wander the romantic streets of Paris together, exploring art, culture, and the magic of the city of love!",
    value: 1,
    views: 4.5,
    Tease: 41,
    posts: 42,
  },

  {
    id: 15,
    name: 'Lily Cruz',
    slug: 'Lily_Cruz',
    icon: model7,
    location: 'Samba in Rio de Janeiro: Lily',
    image: model7BannerImage,
    AboutMe:
      "Oi! I'm Lily, a samba queen with a love for Brazilian culture and rhythm. Let's sizzle under the Rio sun, embracing the energy and passion of samba as we dance our way through the streets of Rio!",
    value: 5,
    views: 3.5,
    Tease: 49,
    posts: 22,
  },
  {
    id: 16,
    name: 'Evelyn Green',
    slug: 'Evelyn_Green',
    icon: model1,
    location: 'Viva Las Vegas: Hazel',
    image: model1BannerImage,
    AboutMe:
      "Hey there! I'm Evelyn, a passionate traveler and adventurer. I thrive on exploring new places and cultures, capturing moments through my lens along the way. Let's embark on exciting journeys together!",
    value: 5,
    views: 3.5,
    Tease: 49,
    posts: 32,
  },
];
